### ISSUE TITLE
请问安装python libzt正常，使用的时候报错是什么原因？

### ISSUE THREAD

**Issue by DarkiT** [neoncloud/Zerotier-port-forward#1]
请问安装python libzt正常，没有任何错误，但是使用的时候错误信息如下：

```
Python 3.6.8 (default, Jan 19 2022, 23:28:49) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-7)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import libzt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.6/site-packages/libzt/__init__.py", line 1, in <module>
    from .libzt import *
  File "/usr/local/lib64/python3.6/site-packages/libzt/libzt.py", line 13, in <module>
    from . import _libzt
ImportError: /usr/local/lib64/python3.6/site-packages/libzt/_libzt.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN8ZeroTier12LinuxNetLinkD1Ev
>>>
```

请问这是什么问题，是我少安装了什么组件吗？

**Comment by neoncloud** [comment]
考虑换到旧版的libzt吧，我在Linux上貌似也遇到了类似的情况。MAC没测试

**Comment by DarkiT** [comment]
请问您当初是用的哪个版本编译成功的？

**Comment by neoncloud** [comment]
> 

你好，我是使用的pip包，版本是1.4.6。

**Comment by DarkiT** [comment]
您方便把您1.4.6的包文件给我吗，pip上好像已经删除了1.4.6的包了
